export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = "DECREMENT_ENTHUSIASM";
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const MAP_INIT = "MAP_INIT";
export type MAP_INIT = typeof MAP_INIT;

export const FEATURELAYER_INIT = "FEATURELAYER_INIT";
export type FEATURELAYER_INIT = typeof FEATURELAYER_INIT;

export const START_EDIT = "START_EDIT";
export type START_EDIT = typeof START_EDIT;

export const END_EDIT = "END_EDIT";
export type END_EDIT = typeof END_EDIT;

// 异步请求
export const FETCH_NO = "FETCH_NO";
export type FETCH_NO = typeof FETCH_NO;

export const FETCH_REQUEST = "FETCH_REQUEST";
export type FETCH_REQUEST = typeof FETCH_REQUEST;

export const FETCH_SUCCESS = "FETCH_SUCCESS";
export type FETCH_SUCCESS = typeof FETCH_SUCCESS;

export const FETCH_ERROR = "FETCH_ERROR";
export type FETCH_ERROR = typeof FETCH_ERROR;

// current
export const VIDEO_SET_CURRENT = "VIDEO_SET_CURRENT";
export type VIDEO_SET_CURRENT = typeof VIDEO_SET_CURRENT;

// video clear
export const VIDEO_CLEAR = "VIDEO_CLEAR";
export type VIDEO_CLEAR = typeof VIDEO_CLEAR;

// marker 异步
export const VIDEO_FETCH_REQUEST = "VIDEO_FETCH_REQUEST";
export type VIDEO_FETCH_REQUEST = typeof VIDEO_FETCH_REQUEST;

export const VIDEO_FETCH_SUCCESS = "VIDEO_FETCH_SUCCESS";
export type VIDEO_FETCH_SUCCESS = typeof VIDEO_FETCH_SUCCESS;

export const VIDEO_FETCH_ERROR = "VIDEO_FETCH_ERROR";
export type VIDEO_FETCH_ERROR = typeof VIDEO_FETCH_ERROR;

// update 异步
export const VIDEO_UPDATE_REQUEST = "VIDEO_UPDATE_REQUEST";
export type VIDEO_UPDATE_REQUEST = typeof VIDEO_UPDATE_REQUEST;

export const VIDEO_UPDATE_SUCCESS = "VIDEO_UPDATE_SUCCESS";
export type VIDEO_UPDATE_SUCCESS = typeof VIDEO_UPDATE_SUCCESS;

export const VIDEO_UPDATE_ERROR = "VIDEO_UPDATE_ERROR";
export type VIDEO_UPDATE_ERROR = typeof VIDEO_UPDATE_ERROR;
