export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = "DECREMENT_ENTHUSIASM";
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const MAP_INIT = "MAP_INIT";
export type MAP_INIT = typeof MAP_INIT;

export const FEATURELAYER_INIT = "FEATURELAYER_INIT";
export type FEATURELAYER_INIT = typeof FEATURELAYER_INIT;

export const START_EDIT = "START_EDIT";
export type START_EDIT = typeof START_EDIT;

export const END_EDIT = "END_EDIT";
export type END_EDIT = typeof END_EDIT;